name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: nuget restore
    - name: Build
      run: msbuild Fridge.sln /verbosity:normal /t:Rebuild /p:Configuration=Release
    - name: Test
      run: msbuild.exe /t:test Fridge.sln
