name: Mobile app build

on:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: nuget restore Fridge-mobile.sln
    - name: Build
      run: msbuild Fridge-mobile.sln /verbosity:normal /t:Rebuild /p:Configuration=Release
    - name: Test
      run: dotnet test src/UT_FridgeApp/UT_FridgeApp.csproj --no-build --verbosity normal --configuration Release
